version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: data_platform_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"